# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ruby:2.5.1
    #    - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/git@github.com:DanielaMoitzi/circleci-example.git

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install # --jobs=4 --retry=3 --path vendor/bundle
            curl -sL https://deb.nodesource.com/setup_8.x | bash -
            apt-get install -y nodejs

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run:
            name: setup database
            command: |
                bundle exec rake db:create
                bundle exec rails db:migrate

      # run tests
      - run:
          name: unit-tests
          command: |
            bin/rails test test/models/*.rb
          
          name: acceptance-tests
          command: |
            bin/rails test test/controllers/*.rb

      

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results